config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do  
    
    get 'login' => 'user_sessions#new', as: :login
    post 'logout' => 'user_sessions#destroy', as: :logout
    
    get 'user_sessions/new'
    get 'user_sessions/create'
    get 'user_sessions/destroy'

    namespace :dashboard do
      resources :cards
      resources :decks
    end

    resources :users
    resources :user_sessions

    post '/check' => 'dashboard/home#check'

    root 'dashboard/home#index'
    root to: 'users#index'

    post "oauth/callback" => "home/oauths#callback"
    get "oauth/callback" => "home/oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "home/oauths#oauth", as: :auth_at_provider

    get 'switch_current_deck' => 'users#switch_current_deck'
  end
end

app/models/card.rb
class Card < ApplicationRecord

  has_attached_file :image, styles: { thumb: "300x300#" }
  belongs_to :user
  belongs_to :deck
  
  with_options presence:true do |a|
    a.validates :original_text
    a.validates :translated_text
    a.validates :review_date
    a.validates :deck_id
  end
  
  validate :words_are_different?

  validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 1.megabyte }

  def words_are_different?
    return errors.add(:empty_fields, 'Fields are empty!') if original_text.empty? || translated_text.empty?
    ot = original_text.split(' ').first.downcase
    tt = translated_text.split(' ').first.downcase
    errors.add(:difference, 'words are the same') if ot == tt
  end

  scope :expired, -> { where('review_date <= ?', DateTime.now) }
  scope :deck, ->(current_deck_id) { expired.where(deck_id: current_deck_id) }
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
  	@cards = current_user.cards
  end

  def show
  	@cards = Card.find(params[:id])
  end

  def new
    @cards = Card.new
    @collection = current_user.decks
  end

  def edit
    @cards = Card.find(params[:id])
    @collection = current_user.decks
  end

  def create
    @cards = current_user.cards.create(card_params)

    if @cards.save
      redirect_to cards_path
    else
      render 'new'
    end
  end

  def update
    @cards = Card.find(params[:id])
 
    if @cards.update(card_params)
      redirect_to cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @cards = Card.find(params[:id])
    @cards.destroy
 
    redirect_to cards_path
  end

  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date, :image, :deck_id)
    end
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  def index
  	@cards = current_user.cards
  end

  def show
  	@cards = Card.find(params[:id])
  end

  def new
    @cards = Card.new
    @collection = current_user.decks
  end

  def edit
    @cards = Card.find(params[:id])
    @collection = current_user.decks
  end

  def create
    @cards = current_user.cards.create(card_params)

    if @cards.save
      redirect_to dashboard_cards_path
    else
      render 'new'
    end
  end

  def update
    @cards = Card.find(params[:id])
 
    if @cards.update(card_params)
      redirect_to dashboard_cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @cards = Card.find(params[:id])
    @cards.destroy
 
    redirect_to dashboard_cards_path
  end

  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date, :image, :deck_id)
    end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  def index
    @decks = current_user.decks
    @current_deck = if current_user.current_deck.nil?
                      "#{t('common.no_deck')}"
                    else
                      current_user.current_deck.title
                    end
  end

  def show
  end

  def new
    @decks = Deck.new
  end

  def create
    @decks = current_user.decks.create(deck_params)

    if @decks.save
      redirect_to dashboard_decks_path
    else
      render 'new'
    end
  end

  def edit
    @decks = Deck.find(params[:id])
  end

  def update
    @decks = Deck.find(params[:id])
 
    if @decks.update(deck_params)
      redirect_to decks_path
    else
      render 'edit'
    end
  end

  def destroy
    @decks = Deck.find(params[:id])
    @decks.destroy
 
    redirect_to decks_path
  end

  private
    def deck_params
      params.require(:deck).permit(:title)
    end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  def index
    card_and_deck
  end

  def check
    @card = Card.find(params[:id])
    @result = SuperMemo.new(@card).translation_correct?(params[:user_text], params[:answer_time])

    if @result
      flash[:result] = t(:correct)      
    else
      flash[:result] = t(:wrong)
    end

    flash[:correct_word] = "#{t(:correct_word)}\"#{@card.original_text}\""
    flash[:users_word] = "#{t(:users_word)}\"#{params[:user_text]}\""
    
    respond_to do |format|
      format.html { render partial: 'check' }
      format.js
      card_and_deck
    end
  end

  private

  def card_and_deck
    @current_deck = current_user.current_deck
    @random_card = if @current_deck.nil?
                     current_user.cards.expired.sample
                   else
                     current_user.cards.deck(@current_deck).sample
                   end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/dashboard/cards/_form.html.erb
<%= simple_form_for [:dashboard, @cards] do |f| %>
    
<% if @cards.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
	<ul>
	  <% @cards.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>	
	</ul>
  </div>
<% end %>

<%= f.input :original_text %>
<%= f.input :translated_text %>
<%= f.input :review_date %>
<%= f.input :image, as: :file %>
<%= f.input :deck_id, collection: @collection %>
<%= f.button :submit, t('cards.form.submit', action: @cards.new_record? ? "#{t('common.create')}" : "#{t('common.change')}") %><br />

<% end %>

app/views/dashboard/cards/edit.html.erb
<h1><%= t('cards.edit.title') %></h1>
 
<%= render 'form' %>

<%= link_to t('common.back'), dashboard_cards_path %>

app/views/dashboard/cards/index.html.erb
<table>
  <tr>
    <th><%= t('cards.index.original') %></th>
    <th><%= t('cards.index.translation') %></th>
    <th><%= t('cards.index.review_date') %></th>
    <th><%= t('cards.index.deck_id') %></th>
    <th colspan="2"></th>
  </tr>
 
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date %></td>
      <td><%= card.deck_id %></td>
      <td><%= link_to t('common.open'), dashboard_card_path(card) %> |</td>
      <td><%= link_to t('common.edit'), edit_dashboard_card_path(card) %> |</td>
      <td><%= link_to t('common.delete'), dashboard_card_path(card),
              method: :delete,
              data: { confirm: t('common.confirmation') } %></td>
    </tr>
  <% end %>
</table>

app/views/dashboard/cards/new.html.erb
<h1><%= t('cards.new.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.back'), dashboard_cards_path %>

app/views/dashboard/cards/show.html.erb
<h1><%= @cards.original_text %> - <%= @cards.translated_text %></h1>
<%= link_to(image_tag(@cards.image.url(:thumb)), @cards.image.url, target: '_blank') if @cards.image.exists? %><br />
<%= link_to t('common.edit'), edit_dashboard_card_path(@cards) %> |
<%= link_to t('common.back'), dashboard_cards_path %>