config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do  
    
    get 'login' => 'user_sessions#new', as: :login
    post 'logout' => 'user_sessions#destroy', as: :logout
    
    get 'user_sessions/new'
    get 'user_sessions/create'
    get 'user_sessions/destroy'

    namespace :dashboard do
      resources :cards
      resources :decks
    end

    resources :users
    resources :user_sessions

    post '/check' => 'dashboard/home#check'

    root 'dashboard/home#index'
    root to: 'users#index'

    post "oauth/callback" => "home/oauths#callback"
    get "oauth/callback" => "home/oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "home/oauths#oauth", as: :auth_at_provider

    get 'switch_current_deck' => 'users#switch_current_deck'
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :card, dependent: :destroy
  belongs_to :user
end

app/controllers/dashboard/cards_controller.rb
class Dashboard::CardsController < ApplicationController
  def index
  	@cards = current_user.cards
  end

  def show
  	@cards = Card.find(params[:id])
  end

  def new
    @cards = Card.new
    @collection = current_user.decks
  end

  def edit
    @cards = Card.find(params[:id])
    @collection = current_user.decks
  end

  def create
    @cards = current_user.cards.create(card_params)

    if @cards.save
      redirect_to dashboard_cards_path
    else
      render 'new'
    end
  end

  def update
    @cards = Card.find(params[:id])
 
    if @cards.update(card_params)
      redirect_to dashboard_cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @cards = Card.find(params[:id])
    @cards.destroy
 
    redirect_to dashboard_cards_path
  end

  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date, :image, :deck_id)
    end
end

app/controllers/dashboard/decks_controller.rb
class Dashboard::DecksController < ApplicationController
  def index
    @decks = current_user.decks
    @current_deck = if current_user.current_deck.nil?
                      "#{t('common.no_deck')}"
                    else
                      current_user.current_deck.title
                    end
  end

  def show
  end

  def new
    @decks = Deck.new
  end

  def create
    @decks = current_user.decks.create(deck_params)

    if @decks.save
      redirect_to dashboard_decks_path
    else
      render 'new'
    end
  end

  def edit
    @decks = Deck.find(params[:id])
  end

  def update
    @decks = Deck.find(params[:id])
 
    if @decks.update(deck_params)
      redirect_to decks_path
    else
      render 'edit'
    end
  end

  def destroy
    @decks = Deck.find(params[:id])
    @decks.destroy
 
    redirect_to decks_path
  end

  private
    def deck_params
      params.require(:deck).permit(:title)
    end
end

app/controllers/dashboard/home_controller.rb
class Dashboard::HomeController < ApplicationController
  def index
    card_and_deck
  end

  def check
    @card = Card.find(params[:id])
    @result = SuperMemo.new(@card).translation_correct?(params[:user_text], params[:answer_time])

    if @result
      flash[:result] = t(:correct)      
    else
      flash[:result] = t(:wrong)
    end

    flash[:correct_word] = "#{t(:correct_word)}\"#{@card.original_text}\""
    flash[:users_word] = "#{t(:users_word)}\"#{params[:user_text]}\""
    
    respond_to do |format|
      format.html { render partial: 'check' }
      format.js
      card_and_deck
    end
  end

  private

  def card_and_deck
    @current_deck = current_user.current_deck
    @random_card = if @current_deck.nil?
                     current_user.cards.expired.sample
                   else
                     current_user.cards.deck(@current_deck).sample
                   end
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = current_user.decks
    @current_deck = if current_user.current_deck.nil?
                      "#{t('common.no_deck')}"
                    else
                      current_user.current_deck.title
                    end
  end

  def show
  end

  def new
    @decks = Deck.new
  end

  def create
    @decks = current_user.decks.create(deck_params)

    if @decks.save
      redirect_to decks_path
    else
      render 'new'
    end
  end

  def edit
    @decks = Deck.find(params[:id])
  end

  def update
    @decks = Deck.find(params[:id])
 
    if @decks.update(deck_params)
      redirect_to decks_path
    else
      render 'edit'
    end
  end

  def destroy
    @decks = Deck.find(params[:id])
    @decks.destroy
 
    redirect_to decks_path
  end

  private
    def deck_params
      params.require(:deck).permit(:title)
    end
end

app/views/dashboard/decks/_form.html.erb
<%= simple_form_for [:dashboard, @decks] do |f| %>
    
<% if @decks.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
	<ul>
	  <% @decks.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>	
	</ul>
  </div>
<% end %>

<%= f.input :title %>
<%= f.button :submit, t('decks.form.submit', action: @decks.new_record? ? "#{t('common.create')}" : "#{t('common.change')}") %><br />

<% end %>

app/views/dashboard/decks/edit.html.erb
<h1><%= t('decks.edit.title') %></h1>
 
<%= render 'form' %>

<%= link_to t('common.back'), dashboard_decks_path %>

app/views/dashboard/decks/index.html.erb
<p><%= link_to t('decks.index.create_new_deck'), new_dashboard_deck_path %> |
<%= link_to t('decks.index.switch_current_deck'), '/switch_current_deck' %></p>

<h4><%= t('decks.index.current_deck') %></h4>
<p><%= @current_deck %></p>

<h4><%= t('decks.index.all_decks') %>:</h4>
<table>
  <tr>
    <th>ID</th>
    <th><%= t('decks.index.deck_title') %></th>
    <th colspan="2"></th>
  </tr>
 
  <% @decks.each do |deck| %>
    <tr>
      <td><%= deck.id %></td>
      <td><%= deck.title %></td>
      <td><%= link_to t('common.edit'), edit_dashboard_deck_path(deck) %></td>
      <td><%= link_to t('common.delete'), dashboard_deck_path(deck),
              method: :delete,
              data: { confirm: t('common.confirmation') } %></td>
    </tr>
  <% end %>
</table>

app/views/dashboard/decks/new.html.erb
<h1><%= t('decks.new.title') %></h1>

<%= render 'form' %>

<%= link_to t('common.back'), dashboard_decks_path %>