config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do  
    
    get 'login' => 'user_sessions#new', as: :login
    post 'logout' => 'user_sessions#destroy', as: :logout
    
    get 'user_sessions/new'
    get 'user_sessions/create'
    get 'user_sessions/destroy'

    namespace :dashboard do
      resources :cards
      resources :decks
    end

    resources :users
    resources :user_sessions

    post '/check' => 'dashboard/home#check'

    root 'dashboard/home#index'
    root to: 'users#index'

    post "oauth/callback" => "home/oauths#callback"
    get "oauth/callback" => "home/oauths#callback" # for use with Github, Facebook
    get "oauth/:provider" => "home/oauths#oauth", as: :auth_at_provider

    get 'switch_current_deck' => 'users#switch_current_deck'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcarder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <span class="navbar-brand">
        <%= link_to "#{t('.title')}", root_path %>
      </span>
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to t('.all_cards'), dashboard_cards_path %> |
            <%= link_to t('.add_card'), new_dashboard_card_path %> |
            <%= link_to t('.decks'), dashboard_decks_path %> |
            <%= link_to t('.login_twitter'), auth_at_provider_path(provider: :twitter) %>
          </li>
        </ul>
        <ul class="nav justify-content-end">
          
          <li class="nav-item <%= "active" if I18n.locale == :ru %>">
            <%= link_to "Рус", { locale: :ru }, class: "nav-link" %>
          </li>
          <li class="nav-item <%= "active" if I18n.locale == :en %>">
            <%= link_to "En", { locale: :en }, class: "nav-link" %>
          </li>
          
          <% if current_user %>
            <li class="nav-item">
              <%= link_to t('.edit_profile'), edit_user_path(current_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to t('.logout'), :logout, method: :post, class: "nav-link" %>
            </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to t('.register'), new_user_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to t('.login'), :login, class: "nav-link" %>
                </li>
          <% end %>
        
        </ul>
      </div>
    </nav>
    

    <main role="main" class="container">
      <div>
          <p id="notice"><%= flash[:notice] %></p>
          <p id="alert"><%= flash[:alert] %></p>
      </div> 
      <div class="starter-template">
        <%= yield %>
      </div>
    </main>
  </body>
</html>